import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar/Navbar";
import Footer from "./components/shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto flex flex-col min-h-screen">
      <Navbar ></Navbar>
     <div className="flex-grow">
     {children}
     </div>
     <Footer ></Footer>
      </body>
    </html>
  );
}
